apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csdpop
  labels:
    codefresh.io/entity: runtime
    codefresh.io/internal: 'true'
spec:
  project: default
  source:
    repoURL: https://github.com/lrochette/ISC_op.git
    targetRevision: HEAD
    path: resources/csdpop/chart
    helm:
      releaseName: csdpop
  destination:
    namespace: csdpop
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
