gitops-runtime:
  global:
    codefresh:
      accountId: 64da76ef9bb32a5d2fd8e0f0
      url: https://lrop.support.cf-cd.com
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      ingress:
        className: nginx
        enabled: true
        hosts:
          - lrcsdpop.support.cf-cd.com
      name: csdpop
  installer:
    skipValidation: true
  tunnel-client:
    enabled: false
